"""
Report Agent — generates and sends Francisco's weekly
business summary every Monday at 8am Perth time.
"""
import logging
from datetime import datetime, timedelta
from tools import ghl, claude_ai

logger = logging.getLogger(__name__)

FRANCISCO_EMAIL = "accounts@seabreezemaintenance.com.au"
WANDER_EMAIL = "wgodinho@gmail.com"
WANDER_CONTACT_ID = "g1Hp5UCnMLVganCyNj93"  # Wander in GHL
FRANCISCO_CONTACT_ID = "lcR0DMJ4JufVyrMAbuLL"


def run():
    """Generate and send weekly report to Francisco."""
    logger.info("📊 Report Agent: Building weekly report...")

    try:
        # Get this week's data
        now = datetime.now()
        week_ago = now - timedelta(days=7)

        contacts = ghl.get_contacts(limit=100)
        opportunities = ghl.get_opportunities()

        # Filter to this week
        new_leads = [
            c for c in contacts
            if "lead-processed" in c.get("tags", [])
            and "(example)" not in c.get("firstName", "").lower()
        ]

        won_jobs = [o for o in opportunities if o.get("status") == "won"]
        open_opps = [o for o in opportunities if o.get("status") == "open"]

        # Estimate revenue (number of won jobs × average job value $350)
        estimated_revenue = len(won_jobs) * 350

        # Build lead summary for Claude
        lead_summary = [
            {
                "name": f"{c.get('firstName')} {c.get('lastName')}",
                "suburb": c.get("city", "Unknown"),
                "tags": c.get("tags", [])
            }
            for c in new_leads[:10]
        ]

        # Generate report with Claude
        report_text = claude_ai.generate_weekly_report(
            leads=lead_summary,
            jobs=won_jobs,
            revenue=estimated_revenue
        )

        # Add report timestamp
        report_with_header = f"""
📊 SEA BREEZE MAINTENANCE — WEEKLY REPORT
Week ending: {now.strftime('%d %B %Y')}
Generated by: Seabreeze AI Agent Stack
{'─' * 40}

{report_text}

{'─' * 40}
📈 QUICK STATS:
• New leads this week: {len(new_leads)}
• Open opportunities: {len(open_opps)}
• Jobs completed: {len(won_jobs)}
• Est. revenue: ${estimated_revenue:,.0f}

Questions? Reply to this email or contact your system operator.
Powered by Impeller Trust × Seabreeze AI
        """.strip()

        # Send as note to Francisco's contact record (SMS/email requires additional GHL config)
        ghl.add_note(FRANCISCO_CONTACT_ID, report_with_header)
        logger.info("📊 Weekly report generated and saved to Francisco's contact record.")
        logger.info(f"\n{report_with_header}")

    except Exception as e:
        logger.error(f"❌ Report Agent error: {e}")
